name: ekt-split-py311
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - pip
  - pip:
      - scikit-multilearn
      - liac-arff